export const MotherArray = [
    {
        Marca: "ASUS",
        Descripcion: "MOTHERBOARD ASUS PRIME B550M-A WIFI AM4",
        Alias: "90MB19X0-M0AAY0",
        DescripcionLarga: "",
        Imagen: "https://http2.mlstatic.com/D_NQ_NP_887116-MLA47059417468_082021-O.webp",
        Precio: 44599,
        SLots: 4,
        Tag:  [ "amd" ],
        Tipo: "motherboard",
        id: "03nFkbOLqC8P2S5WbYFV",
        },

         { 
          Marca: "ASUS",
          Descripcion: "MOTHERBOARD ASUS PRIME A520M-A II/CSM", 
          Precio: 23499,
          Alias: "90MB17H0-M0EAY0",
          Descripcion: "MOTHERBOARD ASUS PRIME A520M-A II/CSM",
          DescripcionLarga: "",
          Imagen: "https://mla-s1-p.mlstatic.com/841088-MLA51919059336_102022-F.jpg",
          Slots: 2,
          Tag:  [ "amd" ],
          Tipo: "motherboard",
          id: "QCgJZNO8e3ePfFcYBSt2",
        },

         { 
         Descripcion: "MOTHERBOARD MSI A520M-A PRO", 
         Imagen: "https://http2.mlstatic.com/D_NQ_NP_887342-MLA44016949854_112020-W.jpg", 
         Slots: 2, 
         Alias: "911-7C96-017",
         Marca: "MSI",
         Precio: 20999,
         Tag:  [ "amd" ],
         Tipo: "motherboard",
         id: "R4xWdHFFaKW1EnEIjfIT",
          },
          
          { 
           Tipo: "motherboard",
           Descripcion: "MOTHERBOARD MSI B450M PRO VDH MAX",
           Alias: "911-7A38-045",
           Imagen: "https://app.contabilium.com/files/explorer/16277/Productos-Servicios/concepto-5952579.png",
           Marca: "MSI",
           Precio: 19999,
           Slots: 4,
           Tag:  [ "amd" ],
           id: "V9aYYb4nJvvTxTXk2r3p",
             },
             
            { 
            Descripcion: "MOTHERBOARD MSI MAG B550 TOMAHAWK",
            Precio: 23999, 
            Alias: "911-TC91-",
            Imagen: "https://http2.mlstatic.com/D_NQ_NP_692087-MLA44918647528_022021-O.jpg",
            Marca: "MSI",
            Slots: 4,
            Tag:  [ "amd" ],
            Tipo: "motherboard",
             id: "dBRhyHdA4ESZh6CeJA0Z",
            },

            {
              Alias: "911-TD20-",
              Descripcion: "MOTHERBOARD MSI B560M-A PRO ",
              Imagen: "https://www.qloud.ar/SITES/IMG/m-y-m-computacion-06-2020/0000000000004719072802950.jpg",
              M2: 1,
              Marca: "MSI",
              Precio: 28999,
              Slots: 4,
              Tag:  [ "intel" ],
              Tipo: "motherboard",
              id: "0yEcjJlybEkBxeWubPGe", 

            },
            {
              Alias: "911-7D46-020",
              Descripcion: "MOTHERBOARD MSI H610M-G PRO",
              Imagen: "https://gorilagames.com/img/Public/1019-producto-motherboard-msi-pro-h610m-g-ddr4-1-4371.jpg",
              Marca: "MSI",
              Precio: 61999,
              Slots: 2,
              Tag:  [ "intel" ],
              Tipo: "motherboard",
              id: "Cyren6EmgXfGpnuemOku",
            }            
]
